### ISSUE TITLE
Complete api-request-builder support for MyActiveCart 

### ISSUE THREAD

**Issue by StarpTech** [commercetools/nodejs#1428]
### Description

See https://github.com/commercetools/nodejs/blob/5397e10af8d69f2f7043869b61c6d52e8c205498/packages/api-request-builder/src/default-services.js#L158-L161

Currently, only `queryOne` is supported but we need all other features.

**Comment by daern91** [comment]
cc @skyriakou

**Comment by daern91** [comment]
Hi @StarpTech, we looked into this one this morning and are not sure what you mean with `all other features`?

According to the docs it's only possible to query the last active cart, and it will be the last modified one. Thus, not possible to create or delete manually.
https://docs.commercetools.com/http-api-projects-me-carts#get-active-cart

Please let us know your thoughts, maybe the feature has changed since you posted this issue since it's still in beta.
