### ISSUE TITLE
Error setting custom Type on Category with no previous custom Type

### ISSUE THREAD

**Issue by xemayebenes** [commercetools/nodejs#320]
### Description
SomeHow jsondiffpatch library is returning a diff that contains an array in the custom type field instead of an object.
Because of this, in `actionMapCustom` function when check 
 `diff.custom.type && diff.custom.type.id` always fails because this diff.custom.type is returning as an array

**Comment by fededevgurus** [comment]
[category-actions.js.patch.txt](https://github.com/commercetools/nodejs/files/1398799/category-actions.js.patch.txt)
It seems that actionsMapCustom function in category-actions file should call diffpatcher.getDeltaValue in order to get the value if diff.custom.type is an array.

This bug has been unnoticed because two reason:

1. Nobody has use it.
2. category-actions test doesn't cover this case because it always works with two categories with defined custom field.

I submit a patch that should work (maybe it is not the best solution, but at least it works).

It would be great if you could fix this issue as soon as possible since we need it working for the project we are currently working.

**Comment by wizzy25** [comment]
Thanks for creating this issue. I'm currently not able to reproduce the problem.
How does your `custom` property look like (in the current and updated category)?

**Comment by fmoro** [comment]
Just try to create a custom field (with fields filled) in a category without a custom field defined.
If it is relevant, my custom property looks like this:

`"custom": {
    "type": {
      "typeId": "type",
      "id": "CustomType ID"
    },
    "fields": {
      "include": [
        {
          "id": "A Category ID",
          "typeId": "category"
        },
        {
          "id": "Another Category ID",
          "typeId": "category"
        }
      ]
    }
  }`

So, the steps to reproduce it are:

1. Create a category **without** custom field defined or just get one **without** custom field defined.
2. Add a custom field to this category **defining the fields attribute**.
3. Try to update the category using the node library syncactions.

You will see that jsondiffpatch library will return an array instead of an object for the custom field (that is normal because you are adding a field, not updating its value), so the `diff.custom.type && diff.custom.type.id` check will return false and it will never create the **setCustomType** action.

The patch I sent 2 weeks ago fix this issue.

**Comment by xemayebenes** [comment]
@wizzy25 See the @fmoro reply please
