### ISSUE TITLE
Create Typescript declaration files

### ISSUE THREAD

**Issue by kevinrambaud** [commercetools/nodejs#329]
### Description
At the moment, it can be not so easy to play with most of the packages without going in depth into the SDK documentation. Did you plan to add typescript declaration files to make our life easier ?

### Expected Behavior
When using a method from a package, the parameters should be typed, auto documented, chained method should be auto suggested by code editor like VS Code, Webstorm.

### Current Behavior
We have some completion when importing method from a middleware but nothing more.

### Context
Tried with VS Code 1.17.2

### Possible Solution
Create declaration files by trying to prioritize by most relevant usage. I'm thinking about the following order :

* sdk-middleware-auth
* sdk-middleware-http
* sdk-client
* api-request-builder (probably the most important)
* sdk-middleware-queue

**Comment by StarpTech** [comment]
What's the status?

**Comment by daern91** [comment]
Hi @StarpTech, I'm afraid this is currently not on the road map. However, I think it's a great idea and would love to see it implemented.

@skyriakou, maybe this is something we could talk about for future development.

**Comment by daern91** [comment]
Hi everyone,

Yesterday we released a TypeScript SDK in its alpha version. Our brilliant @acbeni  has built a typescript code generator which follows the [commercetools platform API specification](https://github.com/commercetools/commercetools-api-reference). So you may expect this one to be much faster updated than the current SDK. Since, at this point, maintainers pretty much only have to press a button to generate the SDK.

For more info, please read the new docs [here](https://commercetools.github.io/nodejs/sdk/api/typescriptSdk.html) and please also note how the code completion is really helpful on all levels. Not only with the different endpoints but also with the responses.

As a final note, we would love to get your feedback on this as it is a first alpha version. Breaking changes are to be expected, and will be documented properly.

Thanks a lot for your patience and looking forward to making it even better.

cc @skyriakou @emmenko @tdeekens @montezume @StarpTech @kevinrambaud

**Comment by StarpTech** [comment]
@daern91 thanks for the update. I will check it out looks pretty interesting.

**Comment by emmenko** [comment]
@daern91 @acbeni FYI: in [appkit](https://github.com/commercetools/merchant-center-application-kit) we're migrating the codebase to TS. One of the packages `@commercetools-frontend/sdk` uses some of the js-sdk packages, which need some TS declarations. In [this PR](https://github.com/commercetools/merchant-center-application-kit/pull/985) I added the basic necessary types in the appkit repo, but obviously it should be a temporary thing as the js-sdk packages should come with their own types by default.

With that in mind, what are your plans regarding this topic?

From my point of view, in general given that we also have the generated TS builder sdk, I would propose to migrate the js-sdk packages to TS as well. I can kick it off and help with the migration but I need your agreement first that this is the path forward.

What do you think?

/cc @tdeekens _for awareness_

**Comment by acbeni** [comment]
@emmenko for me i think that the js sdk should move entirely to typescript, the only thing that is preventing us from doing this so far is a matter of budget, since now we have limited resources scattered on a number of projects, nonetheless i would love to discuss this with @skyriakou and the rest of the team and see if we can prioritize it for a sprint.

I ll keep you updated on the issue.

**Comment by skyriakou** [comment]
@acbeni i have taken this as a topic for our weekly.

**Comment by emmenko** [comment]
Alright thanks, I can also help with that if you are busy with other tasks. Just let me know.

**Comment by ashishhk** [comment]
Closing this issue as its a very specific topic, please follow up this topic on the new issue that address the complete migration of SDKs and Middleware of JS in to TypeScript https://github.com/commercetools/commercetools-sdk-typescript/issues/40
