### ISSUE TITLE
[Sync-actions] Support Price selection

### ISSUE THREAD

**Issue by wizzy25** [commercetools/nodejs#463]
### Description

Add possibility to create `changePrice` action based on `priceSelection`. This is currently only done by comparing the prices IDs, which is not always feasible.

Similar to [this](https://github.com/sphereio/sphere-node-sdk/pull/251)

**Comment by butenkor** [comment]
Thanks for creating an issue. Linked PR recreates prices instead of updating them if new prices array order does not match the order of existing prices: https://github.com/sphereio/sphere-node-sdk/pull/251#discussion_r168198901. We should not depend on the order of prices and always update if possible as price deletion also might remove external discounts set by a different process.

**Comment by wizzy25** [comment]
Array actions in this repo do not have this issue
