### ISSUE TITLE
Add API credentials retrieving package

### ISSUE THREAD

**Issue by Siilwyn** [commercetools/nodejs#50]
### Description
Have a package that retrieves the API credentials from a system like the one we have in the old utils repository. Trying to simplify the behaviour of getting the credentials I came up with three steps. The package will return a promise since it could need to read from the FS.

### Expected Behavior
1. Project name is passed, environment variable: `CT_<project key>` containing `<client id>:<client secret>`.
_Managing multiple projects having to only pass the name._
2. Check environment variables `CT_PROJECT_KEY`, `CT_CLIENT_ID`, `CT_CLIENT_SECRET`.
_For single project usage, nice to have so no project name needs to be passed._
3. Use [dotenv](https://github.com/motdotla/dotenv) package loading values from a file `ct-credentials.env` from the current or `etc` directory.
_Same as the second step but nice to have for users that are not comfortable with setting environment variables._

### Context
This is needed to move on with #27 and good to have for future packages. Avoiding logic duplication like over multiple packages like in [csv-parser-price](https://github.com/commercetools/csv-parser-price/blob/master/src/get-api-credentials.js).

Thoughts?

**Comment by hisabimbola** [comment]
Some thoughts regarding the expected behaviours

> Check environment variables CT_PROJECT_KEY, CT_CLIENT_ID, CT_CLIENT_SECRET.
For single project usage, nice to have so no project name needs to be passed.

I think the reason we moved away from this is because of the risk of using a production project or another project not intented (@PhilippSpo almost fell for this). Less risky if you pass the key you want to use for test when developing

In general, I think we just need something more like what's currently in [sphere-node-utils](https://github.com/sphereio/sphere-node-utils/blob/6c7e9ba1d52964cc463ca7ab5ce7966f67eced9c/src/coffee/helpers/project-credentials-config.coffee)

**Comment by Siilwyn** [comment]
@hisabimbola I would be okay with cutting away option two, for more simplicity. I think the point of 'risk' is not a good reason to do so. Setting these environment variables are the user's own choice, if you work with both development and productions projects you can simply not use them. On the other hand it provides a simpler interface for those with only one project.

Regarding the utils, this is very close to what we have their unless you mean something specifically that's missing? Overall I'd prefer to keep it simpler than the utils.
