### ISSUE TITLE
CSV export without template exports an attribute twice

### ISSUE THREAD

**Issue by VasumathiJayakumar** [commercetools/nodejs#728]
### Support reference number

SUPPORT-3840

### Description

While exporting products without a template the attribute is exported twice.

### Expected Behavior

Attribute exported once 

### Current Behavior

Attribute executed twice `color, color.de`

**Comment by junajan** [comment]
Hello @VasumathiJayakumar, @daern91 ..

There is a difference in full product export here in `product-json-to-csv` and in the old `sphere-node-product-csv-sync` module. For example when we have `LTEXT` and `LENUM` attributes and the selected language is `de`:
```js
[
	{
		"name": "color",
		"value": {
			"en": "red",
			"de": "rot"
		}
	},
	{
		"name": "lenumAttr",
		"value": {
		  "key": "key123",
		  "label": {
		    "en": "labelEn",
		    "de": "labelDe"
		  }
		}
	}
]
```
Using `csv-sync` module we get:
```csv
color.de,lenumAttr
rot,key123
```

Using `product-json-to-csv` we get:
```csv
color,color.en,color.de,lenumAttr,lenumAttr.en,lenumAttr.de
rot,red,rot,key123,labelEn,labelDe
```

So in case of `csv-sync` we don't get a real full export because it still returns only one label based on selected language while `product-json-to-csv` returns in all labels and for `ltext` attributes it prefills `color` with the internationalized label based on the selected language (so we can access only `color` but also `color.de`)

Please let me know what is preferred behaviour - I would vote for exporting all data in full export.

**Comment by daern91** [comment]
In above example I dont understand how `color` can be mapped to `rot`?
```
	{
		"name": "color",
		"value": {
			"en": "red",
			"de": "rot"
		}
	},
```
I think this would instead return the following
```
color,color.en,color.de
,red,rot
```

If my example is correct, I think it would make more sense to not export `color` if the value is an Object since that would indicate we have at least one language and `color` itself will always be an exported empty column.

WDYT @junajan?

**Comment by VasumathiJayakumar** [comment]
@daern91 if the language is set to `de` then the `color` will be mapped to `rot`.

@junajan Is this correct?

**Comment by junajan** [comment]
As @VasumathiJayakumar said - currently it takes the selected language (in our case `DE`) and saves `color[lang]` also as `color` - so we can access labels from the selected language "more easily"

I tested csv-sync (CSV and XLSX) and in full export it exports ltext values from selected language only - eg: `color.de`.

**Comment by junajan** [comment]
So far we have two options when doing a full export. We can duplicate that value or leave `ltext` values only with language codes `color.de,color.en` ..

The benefits of having it not duplicated are:
 - simpler code
 - a possibility to distinguish between `ltext` values `color.de,color.en` from lenum `color(lenum key),color.en(en label),color.de(de label)`

**Comment by daern91** [comment]
That sounds great to me, @junajan! 

@VasumathiJayakumar, is above in alignment with what users are expecting? If so, IMO we can proceed and put this one into code.

**Comment by VasumathiJayakumar** [comment]
@daern91 IMHO user expects the value with languages they set during the full export. So I would also agree with @junajan

**Comment by VasumathiJayakumar** [comment]
@junajan My vote is for  "leave `ltext` values only with language codes` color.de,color.en` .."

**Comment by junajan** [comment]
Oki, I will take it as the next task - because it also affects `product-json-to-xlsx` module
